### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by ljcool2006** [openai/jukebox#103]
I followed the README and when I got to the "Sampling from scratch" section and try the command, this happens:

`(jukebox) D:\Bebble\jukebox\jukebox>python jukebox/sample.py --model=5b_lyrics --name=sample_5b --levels=3 --sample_length_in_seconds=20 \ --total_sample_length_in_seconds=180 --sr=44100 --n_samples=6 --hop_fraction=0.5,0.5,0.125
Using cuda True
{'name': 'sample_5b', 'levels': 3, 'sample_length_in_seconds': 20, 'total_sample_length_in_seconds': 180, 'sr': 44100, 'n_samples': 6, 'hop_fraction': (0.5, 0.5, 0.125)}
Setting sample length to 881920 (i.e. 19.998185941043083 seconds) to be multiple of 128
Downloading from gce
Traceback (most recent call last):
  File "jukebox/sample.py", line 275, in <module>
    fire.Fire(run)
  File "D:\Bebble\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\Bebble\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\Bebble\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/sample.py", line 272, in run
    save_samples(model, device, hps, sample_hps)
  File "jukebox/sample.py", line 177, in save_samples
    vqvae, priors = make_model(model, device, hps)
  File "d:\bebble\jukebox\jukebox\jukebox\make_models.py", line 181, in make_model
    vqvae = make_vqvae(setup_hparams(vqvae, dict(sample_length=hps.get('sample_length', 0), sample_length_in_seconds=hps.get('sample_length_in_seconds', 0))), device)
  File "d:\bebble\jukebox\jukebox\jukebox\make_models.py", line 85, in make_vqvae
    restore(hps, vqvae, hps.restore_vqvae)
  File "d:\bebble\jukebox\jukebox\jukebox\make_models.py", line 54, in restore
    checkpoint = load_checkpoint(checkpoint_path)
  File "d:\bebble\jukebox\jukebox\jukebox\make_models.py", line 37, in load_checkpoint
    checkpoint = t.load(restore, map_location=t.device('cpu'))
  File "D:\Bebble\miniconda3\envs\jukebox\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\Bebble\miniconda3\envs\jukebox\lib\site-packages\torch\serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input`

**Comment by prafullasd** [comment]
The download failed, you'll need to delete the download cache in ~/.cache and redownload, check #25

**Comment by ljcool2006** [comment]
I am using Windows.
