### ISSUE TITLE
EOFError: Ran out of input running any example

### ISSUE THREAD

**Issue by NoiseGener8r** [openai/jukebox#120]
I have tried deleting the .cache folder and its contents several times, as well as running all examples and trying to run it with my own music.

`Traceback (most recent call last):
  File "jukebox/sample.py", line 279, in <module>
    fire.Fire(run)
  File "C:\Users\rfnoi\.conda\envs\jukebox2\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\rfnoi\.conda\envs\jukebox2\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\rfnoi\.conda\envs\jukebox2\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/sample.py", line 276, in run
    save_samples(model, device, hps, sample_hps)
  File "jukebox/sample.py", line 181, in save_samples
    vqvae, priors = make_model(model, device, hps)
  File "c:\users\rfnoi\jukebox\jukebox\make_models.py", line 191, in make_model
    vqvae = make_vqvae(setup_hparams(vqvae, dict(sample_length=hps.get('sample_length', 0), sample_length_in_seconds=hps.get('sample_length_in_seconds', 0))), device)
  File "c:\users\rfnoi\jukebox\jukebox\make_models.py", line 95, in make_vqvae
    restore_model(hps, vqvae, hps.restore_vqvae)
  File "c:\users\rfnoi\jukebox\jukebox\make_models.py", line 55, in restore_model
    checkpoint = load_checkpoint(checkpoint_path)
  File "c:\users\rfnoi\jukebox\jukebox\make_models.py", line 37, in load_checkpoint
    checkpoint = t.load(restore, map_location=t.device('cpu'))
  File "C:\Users\rfnoi\.conda\envs\jukebox2\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\rfnoi\.conda\envs\jukebox2\lib\site-packages\torch\serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input`

**Comment by zdhoward** [comment]
I keep hitting this issue on Windows too.
Deleting the .cache doesn't seem to change anything.

I experience this anytime I run any example or I try to sample my own audio files.

**Comment by nbinobied** [comment]
I had similar issue with the start of training the vqvae, I was able to fix it by changing the number of workers in `train.py` in line number 300 from `hps.bs_sample = hps.nworkers = hps.bs` to `hps.bs_sample = hps.nworkers = 0`
