### ISSUE TITLE
Sampling from scratch failed, help plz

### ISSUE THREAD

**Issue by Apokar** [openai/jukebox#147]
I followed README.MD to create conda env and it was very successful
But when I run 
> python jukebox/sample.py --model=5b_lyrics --name=sample_5b --levels=3 --sample_length_in_seconds=20 --total_sample_length_in_seconds=180 --sr=44100 --n_samples=6 --hop_fraction=0.5,0.5,0.125

I got :

> Using cuda True
> {'name': 'sample_5b', 'levels': 3, 'sample_length_in_seconds': 20, 'total_sample_length_in_seconds': 180, 'sr': 44100, 'n_samples': 6, 'hop_fraction': (0.5, 0.5, 0.125)}
> Setting sample length to 881920 (i.e. 19.998185941043083 seconds) to be multiple of 128
> Downloading from gce
> Traceback (most recent call last):
>   File "jukebox/sample.py", line 279, in <module>
>     fire.Fire(run)
>   File "/opt/h/anaconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
>     component_trace = _Fire(component, args, context, name)
>   File "/opt/h/anaconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
>     component, remaining_args)
>   File "/opt/h/anaconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
>     result = fn(*varargs, **kwargs)
>   File "jukebox/sample.py", line 276, in run
>     save_samples(model, device, hps, sample_hps)
>   File "jukebox/sample.py", line 181, in save_samples
>     vqvae, priors = make_model(model, device, hps)
>   File "/opt/h/projectCodes/juke/jukebox/jukebox/make_models.py", line 191, in make_model
>     vqvae = make_vqvae(setup_hparams(vqvae, dict(sample_length=hps.get('sample_length', 0), sample_length_in_seconds=hps.get('sample_length_in_seconds', 0))), device)
>   File "/opt/h/projectCodes/juke/jukebox/jukebox/make_models.py", line 95, in make_vqvae
>     restore_model(hps, vqvae, hps.restore_vqvae)
>   File "/opt/h/projectCodes/juke/jukebox/jukebox/make_models.py", line 55, in restore_model
>     checkpoint = load_checkpoint(checkpoint_path)
>   File "/opt/h/projectCodes/juke/jukebox/jukebox/make_models.py", line 37, in load_checkpoint
>     checkpoint = t.load(restore, map_location=t.device('cpu'))
>   File "/opt/h/anaconda3/envs/jukebox/lib/python3.7/site-packages/torch/serialization.py", line 526, in load
>     if _is_zipfile(opened_file):
>   File "/opt/h/anaconda3/envs/jukebox/lib/python3.7/site-packages/torch/serialization.py", line 76, in _is_zipfile
>     if ord(magic_byte) != ord(read_byte):
> TypeError: ord() expected a character, but string of length 0 found

**Comment by Apokar** [comment]
my cuda is : Cuda compilation tools, release **10.0**, V10.0.130 
I run this on Linux: **Ubuntu 16.04.5 LTS**
GPU: TESLA P-100


need some help please~

**Comment by Apokar** [comment]
it is because it downloaded an empty vqvae.pth.tar , I downloaded  it from [https://storage.googleapis.com/jukebox-assets/models/1b/vqvae.pth.tar](url) to solve it ,but it need to download more that this file, oh my Internet issues!
