### ISSUE TITLE
What the heck is going on with running this project on WIN 10?

### ISSUE THREAD

**Issue by Porkechebure** [openai/jukebox#181]
I spent a good day trying to run this thing on Win 10, and all I got was errors. Errors. And again..... errors!
I followed step by syep your install guide provided at [jukebox github](https://github.com/openai/jukebox/).
Now I will list all the funny things happened so at least some poor devil might avoid to pull his hair trying to avoid this junk mass of bugs rigged togheter. I am very pragmatic and I like to rant. So this will be filled with hatred towards the author and resolutive commands which will get you out of trouble. Also, it's kinda better (or it seems that the whole things works better when done on it) to use git bash for it.

So, following the installation, the first thing happened:

**NUMBER 1**

**pip install ./tensorboardX** threw a whole lot of errors that begin with:

> ERROR: Command errored out with exit status 1:
>    command: 'C:\ProgramData\Miniconda3\envs\jukebox\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\Temp\\pip-req-build-tc2lgd1d\\setup.py'"'"'; __file__='"'"'C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\Temp\\pip-req-build-tc2lgd1d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-wheel-qqwbochf'
>        cwd: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-req-build-tc2lgd1d\

To solve this, I had to find a trick somewhere, which was to initialize miniconda locally in the folder of the project.
To do this you have to go in GIT bash, change dir to the main jukebox folder and do:

`$ . C:/ProgramData/Miniconda3/etc/profile.d/conda.sh`

Change the dir where you installed miniconda.
Then launch again the setup and it should go without errors.

**NUMBER 2**
torch install not work.
[this issue](https://github.com/openai/jukebox/issues/127)
I'm not going even to venture in the bizzarre solutions proposed.
This just worked (and dowloaded a whopping 2GB of libs).

First
` conda install pytorch torchvision -c pytorch
`then
` pip3 install torch torchvision`

I know they are in the install guide, but they don't work.

**NUMBER 3**
mpi4py does not work.

conda install mpi4py=3.0.3 does not work.
As suggested i did pip install mpi4py==3.0.3 and it seemed to go....
until you  try to run it.... and you get:
ImportError: DLL load failed: The specified module could not be found. 

Turns out this thing uses some weird microsoft library that the software author didn't mention.
[Microsoft MPI v10.0](https://www.microsoft.com/en-us/download/confirmation.aspx?id=57467)

After installing it I got another error (eheh)

**NUMBER 4**

> RuntimeError("Failed to initialize NCCL")à
Turns out this piece of brown matter, uses some nvidia weird libraries called NCCL, which apparently are available ONLY ON LINUX and which also require a dev account to be downloaded.
[NCCL Link](https://developer.nvidia.com/nccl)

Found also a [download link](https://anaconda.org/anaconda/nccl) for them, but it's only for linux.

So I wasted hours because these idiots forgot to mention that this crap doesn't run on windows.
Awesome!

A massive FUCK YOU to who developed this.

**Comment by Randy1435** [comment]
Okay so first of all. Work on respect. No one gonna help you if you're not respectfull ( except me :3 ) It's no ones faulths that you aren't able to get this to run on your machine. Not blaming you, it's hard do download something from python. 

Second of all, what are your specifications? If you have a 3090 or below, you can forget running this on your machine and need to run a colab notebook. 

Third of all (you guessed it) Use a colab notebook. It's way easier and offers you acces to Nvidia's PCIE v100 (It's rly good m8) tho it may be a hassle. Below will be a time thingie so you can expect how long it takes for around 1 minute of audio to be generated. There will also be a link to the notebook.

Fourth of all, you can probably run this on Windows somehow but if you want to boost your times, linux runs better.

Fifth, when opening an issue, make sure you always show respect, This is basically number one but better.

Audio generation table:

- 1 minute not upsampled (Level_2) takes 60 minutes.
- 1 minute halfway upsampled (Level_1) takes 2 hours (Not including previous time)
- 1 minute fully upsampled (level_0) takes 6 hours (Not including previous time)

These are all for a batch size of 3 with the 5b_lyrics model.

Link to colab: https://colab.research.google.com/github/SMarioMan/jukebox/blob/master/jukebox/Interacting_with_Jukebox.ipynb

**Comment by Randy1435** [comment]
Oh, something else. Ancestral is not the way to go, you may get pretty good results but that's because you're lucky. Ancestral doesn't normally give good results. I'd recommend that you get a song of choice and cut off a part with like 5 seconds of the music (Including the singer singing) and give that to the computer along with the lyrics.

**Comment by Porkechebure** [comment]
> Okay so first of all. Work on respect. No one gonna help you if you're not respectfull ( except me :3 ) It's no ones faulth that you aren't able to get this to run on your machine. Not blaming you, it's hard to download something from python.
Not from someone who releases this kind of sourcecode making people waste time. They deserve everything I said and worse.
They should work on respecting other people time.

 
> Second of all, what are your specifications? If you have a 3090 or below, you can forget running this on your machine and need to run a colab notebook.

What is a 3090? Is the year in which this code will be fixed?
 
> Third of all (you guessed it) Use a colab notebook. It's way easier and offers you acces to Nvidia's PCIE v100 (It's rly good m8) tho it may be a hassle. Below will be a time thingie so you can expect how long it takes for around 1 minute of audio to be generated on those GPU's. There will also be a link to the notebook.

The heck is a colab notebook?

> Fourth of all, you can probably run this on Windows somehow but if you want to boost your times, linux runs better.

Except that I despise linux and the whole community around it. But, in this case I have to work with it. Also this explains the low quality of the code. Rants apart, ok, I will go with linux. I'm trying to put up a docker ubuntu container.

> Fifth, when opening an issue, make sure you always show respect, This is basically number one but better.

As said, I bring much respect to who deserve it, and the opposite to who writes stuff with his feets thinking with the ass, instead of using hands and thinking with the brain.

> Audio generation table:
> 
> * 1 minute not upsampled (Level_2) takes 60 minutes.
> * 1 minute halfway upsampled (Level_1) takes 2 hours (Not including previous time)
> * 1 minute fully upsampled (level_0) takes 6 hours (Not including previous time)
> 
> These are all for a batch size of 3 with the 5b_lyrics model.

Well, that's useful to know, this will however run on a pc which will be always on, many hours every day. So for me it's not a big deal if it takes a lot of time.

> Link to colab: https://colab.research.google.com/github/SMarioMan/jukebox/blob/master/jukebox/Interacting_with_Jukebox.ipynb

I'll check out and try to find out what these colab are. They look like shared PCs?

Thank you for your help.

Another question, if you can answer please:

Can I train this software on my own songs? Like train it on some of my own made tracks and forge the AI around them?
Does it work with foreign languages if you train it from scratch?

Like if I sing in french, or swedish, does it work? There is a way to do it?

If yes, could you please explain how to do it?

Thank you for your time.

**Comment by Randy1435** [comment]
**Answers to your questions:**

I referred to the RTX 3090 by Nvidia. If you have one of them or you have a slower one, you can forget doing this on your own PC.

A colab notebook is something free that is able to let you run anything python related on Google's GPU's.

You can train this on your own songs but you need a big dataset of a certain singer. I am not sure if you can make it sing in french because it is mainly trained on English songs (When not trained) but if you train it yourself you may still run into these problems:

- It takes a long while (more than 2 weeks if you don't have a really good GPU)
- You need a big dataset if you actually want it to make it sing swedish or french.

I do not know how to make the neural network learn.

**Other usefull things:**

On the colab notebook you only get about 12 hours of runtime.

You need to train on your own computer as I assume that you can't train a big dataset on google colab because it'll still take more than 12 hours to train a dataset

**Comment by Porkechebure** [comment]
> **Answers to your questions:**
> 
> I referred to the RTX 3090 by Nvidia. If you have one of them or you have a slower one, you can forget doing this on your own PC.
> 
> A colab notebook is something free that is able to let you run anything python related on Google's GPU's.
> 
> You can train this on your own songs but you need a big dataset of a certain singer. I am not sure if you can make it sing in french because it is mainly trained on English songs (When not trained) but if you train it yourself you may still run into these problems:
> 
> * It takes a long while (more than 2 weeks if you don't have a really good GPU)
> * You need a big dataset if you actually want it to make it sing swedish or french.
> 
> I do not know how to make the neural network learn.
> 
> **Other usefull things:**
> 
> On the colab notebook you only get about 12 hours of runtime.
> 
> You need to train on your own computer as I assume that you can't train a big dataset on google colab because it'll still take more than 12 hours to train a dataset

Ok, thank you again.
I need to ask you some more info., if you kindly can provide them.

I would like to know more on how to carry on the aforementioned activities.

How to train the AI on my own songs in another language? How to feed them?
I need the commands, the scripts and what more or like to type in the commandline. Or a general direction on how to do it.
I can't see clear informations on how to clear their database and make my own. I have a lot of songs, I have lot of material to feed, and lot of time to give on it while I am away from keyboard.
How one can start such activity?

Moreover, I would like to know where to find more informations on the models and on how to fiddle and tweak the whole program.
5b, 5b_lyrics etc etc don't give me any info on what I'm doing.

From their help guide I can't even understand how to feed one song of my own on the AI to generate a new one. Can you please lead me and help me to understand?

**Comment by Randy1435** [comment]
I do not know how you can train The neural network. You don't need to clear their database.

There are 3 models. 1b_lyrics, 5b, 5b_lyrics.
1b_lyrics: Trained on a billion parameters and supports lyrics and singing (Available on colab)
5b: Trained on 5 billion parameters and does not support lyrics (Not available on colab due to an error)
5b_lyrics: Trained on 5 billion parametes and supports lyrics and singing (Available on colab)

1b_lyrics can generate 8 samples in an hour while 5b_lyrics can only generate 3 although 5b_lyrics is a lot better than the 1b_lyrics.

To feed your own song to the AI, make sure it is English first (Sorry mate). It does not support any other languange. You should get an intresting part with English vocals and music. Just cut 12 seconds of any English song and then you have something to feed to the neural network.

So if you're using colab (which you should) then you should run the second, third and fourth cell but before you run the fourth cell, change the HPS name to a directy that doesnt exist yet. So just give it a name, "/content/gdrive/My Drive/song" should work. Now run that cell. if you have a sample you can make it generate more of it, Just change the cell with "Primed" and specify your directory to the song when you uploaded it to your drive and specify how long that song is.

then click the cell "sample_hps = Hyperparams.." Ignore the previous cell. Change your sample in length seconds to 72 or something like that and then run that cell. Specify your artist. If your artist is not in the database, just specify your artist as "unknown". Choose your genre and the lyrics and then run it.

Now run the last 2 cells after the "choosing your lyrics and genre" and it now should do its thing.

**### NOTE:**
It can take up to 1,2 hours to run that last cell and it will only create level 2. Listen to the music that it generated and choose if you like it or not. If you do you can run the 3 cells after that last cell you ran. (the audio one just displays the first result, you'll have 3 in your google drive.)

Downloading the 5b_lyrics model can take up to 8 minutes. Please have patience.

It takes 9 hours in total for 3 whole samples to be done and upsampled fully.

Other links:

Colab file: https://colab.research.google.com/github/SMarioMan/jukebox/blob/master/jukebox/Interacting_with_Jukebox.ipynb
Tutorial: https://medium.com/@marconan/openai-jukebox-and-google-colab-tutorial-54871a139d3a

**Comment by Randy1435** [comment]
This colab file also requires access to your google drive.

**Comment by Porkechebure** [comment]
> I do not know how you can train The neural network. You don't need to clear their database.
> 
> There are 3 models. 1b_lyrics, 5b, 5b_lyrics.
> 1b_lyrics: Trained on a billion parameters and supports lyrics and singing (Available on colab)
> 5b: Trained on 5 billion parameters and does not support lyrics (Not available on colab due to an error)
> 5b_lyrics: Trained on 5 billion parametes and supports lyrics and singing (Available on colab)
> 
> 1b_lyrics can generate 8 samples in an hour while 5b_lyrics can only generate 3 although 5b_lyrics is a lot better than the 1b_lyrics.
> 
> To feed your own song to the AI, make sure it is English first (Sorry mate). It does not support any other languange. You should get an intresting part with English vocals and music. Just cut 12 seconds of any English song and then you have something to feed to the neural network.
> 
> So if you're using colab (which you should) then you should run the second, third and fourth cell but before you run the fourth cell, change the HPS name to a directy that doesnt exist yet. So just give it a name, "/content/gdrive/My Drive/song" should work. Now run that cell. if you have a sample you can make it generate more of it, Just change the cell with "Primed" and specify your directory to the song when you uploaded it to your drive and specify how long that song is.
> 
> then click the cell "sample_hps = Hyperparams.." Ignore the previous cell. Change your sample in length seconds to 72 or something like that and then run that cell. Specify your artist. If your artist is not in the database, just specify your artist as "unknown". Choose your genre and the lyrics and then run it.
> 
> Now run the last 2 cells after the "choosing your lyrics and genre" and it now should do its thing.
> 
> **### NOTE:**
> It can take up to 1,2 hours to run that last cell and it will only create level 2. Listen to the music that it generated and choose if you like it or not. If you do you can run the 3 cells after that last cell you ran. (the audio one just displays the first result, you'll have 3 in your google drive.)
> 
> Downloading the 5b_lyrics model can take up to 8 minutes. Please have patience.
> 
> It takes 9 hours in total for 3 whole samples to be done and upsampled fully.
> 
> Other links:
> 
> Colab file: https://colab.research.google.com/github/SMarioMan/jukebox/blob/master/jukebox/Interacting_with_Jukebox.ipynb
> Tutorial: https://medium.com/@marconan/openai-jukebox-and-google-colab-tutorial-54871a139d3a

Ok so the whole thing is really limited and out of reach of casual users like me from what I can see....

Well.... thank you for your time. Still interested in training the AI with my own songs but hell knows how to do it

**Comment by Porkechebure** [comment]
For your info:
I ran successfully the whole setup on ubuntu, but when running the sampling I get:

> (jukebox) root@7596d667dc1c:/jukebox# python jukebox/sample.py --model=5b_lyrics --name=sample_5b --levels=3 --sample_length_in_seconds=20 --total_sample_length_in_seconds=180 --sr=44100 --n_samples=6 --hop_fraction=0.5,0.5,0.125
> Traceback (most recent call last):
>   File "jukebox/sample.py", line 8, in <module>
>     from jukebox.utils.audio_utils import save_wav, load_audio
>   File "/jukebox/jukebox/utils/audio_utils.py", line 4, in <module>
>     import soundfile
>   File "/root/miniconda3/envs/jukebox/lib/python3.7/site-packages/soundfile.py", line 142, in <module>
>     raise OSError('sndfile library not found')
> OSError: sndfile library not found

So it's not working even on linux..... Depressing to say the least

**Comment by Mouradif** [comment]
Maybe update the README.md to mention that it only workd on Linux. I've just spent 4 hours trying to figure out what was wrong and to make it work on Windows, including the first few steps of this issue before realizing I've ruined my mobile data plan for nothing.

**Comment by Porkechebure** [comment]
> Maybe update the README.md to mention that it only workd on Linux. I've just spent 4 hours trying to figure out what was wrong and to make it work on Windows, including the first few steps of this issue before realizing I've ruined my mobile data plan for nothing.

I feel your pain bro

**Comment by itsmeow** [comment]
@Porkechebure Your CUDA driver is not up to date enough to use CUDA Toolkit v10.
https://forums.developer.nvidia.com/t/error-cuda-driver-version-is-insufficient-for-cuda-runtime-version/66006

**Comment by cicinwad** [comment]
> I spent a good day trying to run this thing on Win 10, and all I got was errors. Errors. And again..... errors! I followed step by syep your install guide provided at [jukebox github](https://github.com/openai/jukebox/). Now I will list all the funny things happened so at least some poor devil might avoid to pull his hair trying to avoid this junk mass of bugs rigged togheter. I am very pragmatic and I like to rant. So this will be filled with hatred towards the author and resolutive commands which will get you out of trouble. Also, it's kinda better (or it seems that the whole things works better when done on it) to use git bash for it.
> 
> So, following the installation, the first thing happened:
> 
> **NUMBER 1**
> 
> **pip install ./tensorboardX** threw a whole lot of errors that begin with:
> 
> > ERROR: Command errored out with exit status 1:
> > command: 'C:\ProgramData\Miniconda3\envs\jukebox\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-req-build-tc2lgd1d\setup.py'"'"'; **file**='"'"'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-req-build-tc2lgd1d\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-wheel-qqwbochf'
> > cwd: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-req-build-tc2lgd1d\
> 
> To solve this, I had to find a trick somewhere, which was to initialize miniconda locally in the folder of the project. To do this you have to go in GIT bash, change dir to the main jukebox folder and do:
> 
> `$ . C:/ProgramData/Miniconda3/etc/profile.d/conda.sh`
> 
> Change the dir where you installed miniconda. Then launch again the setup and it should go without errors.
> 
> **NUMBER 2** torch install not work. [this issue](https://github.com/openai/jukebox/issues/127) I'm not going even to venture in the bizzarre solutions proposed. This just worked (and dowloaded a whopping 2GB of libs).
> 
> First `conda install pytorch torchvision -c pytorch`then ` pip3 install torch torchvision`
> 
> I know they are in the install guide, but they don't work.
> 
> **NUMBER 3** mpi4py does not work.
> 
> conda install mpi4py=3.0.3 does not work. As suggested i did pip install mpi4py==3.0.3 and it seemed to go.... until you try to run it.... and you get: ImportError: DLL load failed: The specified module could not be found.
> 
> Turns out this thing uses some weird microsoft library that the software author didn't mention. [Microsoft MPI v10.0](https://www.microsoft.com/en-us/download/confirmation.aspx?id=57467)
> 
> After installing it I got another error (eheh)
> 
> **NUMBER 4**
> 
> > RuntimeError("Failed to initialize NCCL")à
> > Turns out this piece of brown matter, uses some nvidia weird libraries called NCCL, which apparently are available ONLY ON LINUX and which also require a dev account to be downloaded.
> > [NCCL Link](https://developer.nvidia.com/nccl)
> 
> Found also a [download link](https://anaconda.org/anaconda/nccl) for them, but it's only for linux.
> 
> So I wasted hours because these idiots forgot to mention that this crap doesn't run on windows. Awesome!
> 
> A massive FUCK YOU to who developed this.

Try windows 8?

**Comment by Porkechebure** [comment]
> > I spent a good day trying to run this thing on Win 10, and all I got was errors. Errors. And again..... errors! I followed step by syep your install guide provided at [jukebox github](https://github.com/openai/jukebox/). Now I will list all the funny things happened so at least some poor devil might avoid to pull his hair trying to avoid this junk mass of bugs rigged togheter. I am very pragmatic and I like to rant. So this will be filled with hatred towards the author and resolutive commands which will get you out of trouble. Also, it's kinda better (or it seems that the whole things works better when done on it) to use git bash for it.
> > So, following the installation, the first thing happened:
> > **NUMBER 1**
> > **pip install ./tensorboardX** threw a whole lot of errors that begin with:
> > > ERROR: Command errored out with exit status 1:
> > > command: 'C:\ProgramData\Miniconda3\envs\jukebox\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-req-build-tc2lgd1d\setup.py'"'"'; **file**='"'"'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-req-build-tc2lgd1d\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-wheel-qqwbochf'
> > > cwd: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-req-build-tc2lgd1d\
> > 
> > 
> > To solve this, I had to find a trick somewhere, which was to initialize miniconda locally in the folder of the project. To do this you have to go in GIT bash, change dir to the main jukebox folder and do:
> > `$ . C:/ProgramData/Miniconda3/etc/profile.d/conda.sh`
> > Change the dir where you installed miniconda. Then launch again the setup and it should go without errors.
> > **NUMBER 2** torch install not work. [this issue](https://github.com/openai/jukebox/issues/127) I'm not going even to venture in the bizzarre solutions proposed. This just worked (and dowloaded a whopping 2GB of libs).
> > First `conda install pytorch torchvision -c pytorch`then ` pip3 install torch torchvision`
> > I know they are in the install guide, but they don't work.
> > **NUMBER 3** mpi4py does not work.
> > conda install mpi4py=3.0.3 does not work. As suggested i did pip install mpi4py==3.0.3 and it seemed to go.... until you try to run it.... and you get: ImportError: DLL load failed: The specified module could not be found.
> > Turns out this thing uses some weird microsoft library that the software author didn't mention. [Microsoft MPI v10.0](https://www.microsoft.com/en-us/download/confirmation.aspx?id=57467)
> > After installing it I got another error (eheh)
> > **NUMBER 4**
> > > RuntimeError("Failed to initialize NCCL")à
> > > Turns out this piece of brown matter, uses some nvidia weird libraries called NCCL, which apparently are available ONLY ON LINUX and which also require a dev account to be downloaded.
> > > [NCCL Link](https://developer.nvidia.com/nccl)
> > 
> > 
> > Found also a [download link](https://anaconda.org/anaconda/nccl) for them, but it's only for linux.
> > So I wasted hours because these idiots forgot to mention that this crap doesn't run on windows. Awesome!
> > A massive FUCK YOU to who developed this.
> 
> Try windows 8?

Is this supposed to be a solution?
Lol, get the author ass to make something workable, not the poor devils who wants to use it to use old systems.
I should do a win 8 install to use this crap? No

**Comment by Porkechebure** [comment]
Reopened because author though would be nice to close an unsolved issue

**Comment by Mouradif** [comment]
The solution is super simple: update the README.md they won't even do **that**...

And @cicinwad I hope you're proud of your joke the fire was out for more than a year but you decided to send notifications to 4 people to say "Try Windows 8"...

**Comment by cicinwad** [comment]
You know, it has been 9 months, so I want you to use windows 8.1.

**Comment by itsnotlupus** [comment]
I've been running this stuff on Windows 11 just fine.  
The trick of course, is to not run it in Windows, but in WSL2 (Windows subsystem for Linux), effectively a Linux setup running in a virtual machine tightly integrated within Windows.  
It also works in Windows 10, but alas isn't available in windows 8.

There are a number of gotchas in setting this up involving CUDA drivers and a few other things so I wouldn't recommend it for everyone, but it's probably the only way you'll get this (and many other ML projects) running on a windows box.

**Comment by Porkechebure** [comment]
> I've been running this stuff on Windows 11 just fine. The trick of course, is to not run it in Windows, but in WSL2 (Windows subsystem for Linux), effectively a Linux setup running in a virtual machine tightly integrated within Windows. It also works in Windows 10, but alas isn't available in windows 8.
> 
> There are a number of gotchas in setting this up involving CUDA drivers and a few other things so I wouldn't recommend it for everyone, but it's probably the only way you'll get this (and many other ML projects) running on a windows box.

Just show us the bash to do that

**Comment by itsnotlupus** [comment]
> Just show us the bash to do that

Man.. I've long forgotten the precise steps I did here. I don't have a script for this, I just poked at it until it worked.

My advice would be to install WSL (`wsl --install` [and stuff](https://learn.microsoft.com/en-us/windows/wsl/install)), get [CUDA working on WSL](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl), and then follow the install instructions in this repo's readme.

**Comment by Porkechebure** [comment]
> > Just show us the bash to do that
> 
> Man.. I've long forgotten the precise steps I did here. I don't have a script for this, I just poked at it until it worked.
> 
> My advice would be to install WSL (`wsl --install` [and stuff](https://learn.microsoft.com/en-us/windows/wsl/install)), get [CUDA working on WSL](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl), and then follow the install instructions in this repo's readme.

how wsl can access win host hardware to leverage full power of host machine?
