### ISSUE TITLE
Error pip install ./tensorboardX

### ISSUE THREAD

**Issue by WellImDumb** [openai/jukebox#195]
(jukebox) C:\Users\misho\jukebox-master>pip install ./tensorboardX
Processing c:\users\misho\jukebox-master\tensorboardx
Requirement already satisfied: numpy in c:\users\misho\anaconda3\envs\jukebox\lib\site-packages (from tensorboardX==1.8) (1.19.4)
Requirement already satisfied: six in c:\users\misho\anaconda3\envs\jukebox\lib\site-packages (from tensorboardX==1.8) (1.15.0)
Collecting protobuf>=3.6.1
  Using cached protobuf-3.14.0-cp37-cp37m-win_amd64.whl (798 kB)
Building wheels for collected packages: tensorboardX
  Building wheel for tensorboardX (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\misho\Anaconda3\envs\jukebox\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\misho\\AppData\\Local\\Temp\\pip-req-build-0z3hws3x\\setup.py'"'"'; __file__='"'"'C:\\Users\\misho\\AppData\\Local\\Temp\\pip-req-build-0z3hws3x\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\misho\AppData\Local\Temp\pip-wheel-a50q01wy'
       cwd: C:\Users\misho\AppData\Local\Temp\pip-req-build-0z3hws3x\
  Complete output (103 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\tensorboardX
  copying tensorboardX\caffe2_graph.py -> build\lib\tensorboardX
  copying tensorboardX\crc32c.py -> build\lib\tensorboardX
  copying tensorboardX\embedding.py -> build\lib\tensorboardX
  copying tensorboardX\event_file_writer.py -> build\lib\tensorboardX
  copying tensorboardX\onnx_graph.py -> build\lib\tensorboardX
  copying tensorboardX\proto_graph.py -> build\lib\tensorboardX
  copying tensorboardX\pytorch_graph.py -> build\lib\tensorboardX
  copying tensorboardX\record_writer.py -> build\lib\tensorboardX
  copying tensorboardX\summary.py -> build\lib\tensorboardX
  copying tensorboardX\torchvis.py -> build\lib\tensorboardX
  copying tensorboardX\utils.py -> build\lib\tensorboardX
  copying tensorboardX\visdom_writer.py -> build\lib\tensorboardX
  copying tensorboardX\writer.py -> build\lib\tensorboardX
  copying tensorboardX\x2num.py -> build\lib\tensorboardX
  copying tensorboardX\__init__.py -> build\lib\tensorboardX
  running egg_info
  creating tensorboardX.egg-info
  writing tensorboardX.egg-info\PKG-INFO
  writing dependency_links to tensorboardX.egg-info\dependency_links.txt
  writing requirements to tensorboardX.egg-info\requires.txt
  writing top-level names to tensorboardX.egg-info\top_level.txt
  writing manifest file 'tensorboardX.egg-info\SOURCES.txt'
  reading manifest file 'tensorboardX.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*' found under directory 'test'
  warning: no previously-included files matching '*' found under directory 'examples'
  writing manifest file 'tensorboardX.egg-info\SOURCES.txt'
  creating build\lib\tensorboardX\beholder
  copying tensorboardX\beholder\__init__.py -> build\lib\tensorboardX\beholder
  copying tensorboardX\beholder\beholder.py -> build\lib\tensorboardX\beholder
  copying tensorboardX\beholder\file_system_tools.py -> build\lib\tensorboardX\beholder
  copying tensorboardX\beholder\shared_config.py -> build\lib\tensorboardX\beholder
  copying tensorboardX\beholder\video_writing.py -> build\lib\tensorboardX\beholder
  creating build\lib\tensorboardX\proto
  copying tensorboardX\proto\__init__.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\api.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\api_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\attr_value.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\attr_value_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\event.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\event_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\graph.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\graph_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\layout.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\layout_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\node_def.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\node_def_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\plugin_hparams.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\plugin_hparams_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\plugin_mesh.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\plugin_mesh_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\plugin_pr_curve.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\plugin_pr_curve_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\plugin_text.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\plugin_text_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\resource_handle.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\resource_handle_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\step_stats.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\step_stats_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\summary.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\summary_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\tensor.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\tensor_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\tensor_shape.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\tensor_shape_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\types.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\types_pb2.py -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\versions.proto -> build\lib\tensorboardX\proto
  copying tensorboardX\proto\versions_pb2.py -> build\lib\tensorboardX\proto
  installing to build\bdist.win-amd64\wheel
  running install
  W i n d o w s   S u b s y s t e m   f o r   L i n u x   h a s   n o   i n s t a l l e d   d i s t r i b u t i o n s .
   D i s t r i b u t i o n s   c a n   b e   i n s t a l l e d   b y   v i s i t i n g   t h e   M i c r o s o f t   S t   r e :
   h t t p s : / / a k a . m s / w s l s t o r e
   Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\misho\AppData\Local\Temp\pip-req-build-0z3hws3x\setup.py", line 86, in <module>
      tests_require=test_requirements
    File "C:\Users\misho\Anaconda3\envs\jukebox\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\misho\Anaconda3\envs\jukebox\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\misho\Anaconda3\envs\jukebox\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\misho\Anaconda3\envs\jukebox\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\misho\Anaconda3\envs\jukebox\lib\site-packages\wheel\bdist_wheel.py", line 335, in run
      self.run_command('install')
    File "C:\Users\misho\Anaconda3\envs\jukebox\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\misho\Anaconda3\envs\jukebox\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\misho\AppData\Local\Temp\pip-req-build-0z3hws3x\setup.py", line 25, in run
      compileProtoBuf()
    File "C:\Users\misho\AppData\Local\Temp\pip-req-build-0z3hws3x\setup.py", line 13, in compileProtoBuf
      assert res == 0, 'cannot compile protobuf'
  AssertionError: cannot compile protobuf
  ----------------------------------------
  ERROR: Failed building wheel for tensorboardX
  Running setup.py clean for tensorboardX
Failed to build tensorboardX
Installing collected packages: protobuf, tensorboardX
    Running setup.py install for tensorboardX ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\misho\Anaconda3\envs\jukebox\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\misho\\AppData\\Local\\Temp\\pip-req-build-0z3hws3x\\setup.py'"'"'; __file__='"'"'C:\\Users\\misho\\AppData\\Local\\Temp\\pip-req-build-0z3hws3x\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\misho\AppData\Local\Temp\pip-record-q_lduh90\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\misho\Anaconda3\envs\jukebox\Include\tensorboardX'
         cwd: C:\Users\misho\AppData\Local\Temp\pip-req-build-0z3hws3x\
    Complete output (21 lines):
    running install
    W i n d o w s   S u b s y s t e m   f o r   L i n u x   h a s   n o   i n s t a l l e d   d i s t r i b u t i o n s
     D i s t r i b u t i o n s   c a n   b e   i n s t a l l e d   b y   v i s i t i n g   t h e   M i c r o s o f t   S     r e :
     h t t p s : / / a k a . m s / w s l s t o r e
     Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\misho\AppData\Local\Temp\pip-req-build-0z3hws3x\setup.py", line 86, in <module>
        tests_require=test_requirements
      File "C:\Users\misho\Anaconda3\envs\jukebox\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\misho\Anaconda3\envs\jukebox\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\misho\Anaconda3\envs\jukebox\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\misho\Anaconda3\envs\jukebox\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\misho\AppData\Local\Temp\pip-req-build-0z3hws3x\setup.py", line 25, in run
        compileProtoBuf()
      File "C:\Users\misho\AppData\Local\Temp\pip-req-build-0z3hws3x\setup.py", line 13, in compileProtoBuf
        assert res == 0, 'cannot compile protobuf'
    AssertionError: cannot compile protobuf
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\misho\Anaconda3\envs\jukebox\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\misho\\AppData\\Local\\Temp\\pip-req-build-0z3hws3x\\setup.py'"'"'; __file__='"'"'C:\\Users\\misho\\AppData\\Local\\Temp\\pip-req-build-0z3hws3x\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\misho\AppData\Local\Temp\pip-record-q_lduh90\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\misho\Anaconda3\envs\jukebox\Include\tensorboardX' Check the logs for full command output.

**Comment by Randy-H0** [comment]
Hello, I'm probably your only hope here (cause everyone here died apparently) but I'd just recommend going to the colab version and doing that there, doesn't fry your GPU and doesn't take 6 headaches and 9 self-death-threathen moments. It's fast there. Here is the link, Have fun bud and hope to see you soon!

https://colab.research.google.com/github/Broccaloo/Jukebox_mod/blob/master/jukebox/Interacting_with_Jukebox.ipynb

**Comment by anpos231** [comment]
Any updates?
I have the same issue, trying to install on Windows 10.

**Comment by anpos231** [comment]
OK, I think the simplest reason why this does not work is because the install script for tensorboardX is written in bash and not designed for windows 10.

I have managed to install it on windows 10 after few modifications though, I'll run some testing and maybe push a patch later if everything is all right.

**Comment by thomasvdlaan** [comment]
> OK, I think the simplest reason why this does not work is because the install script for tensorboardX is written in bash and not designed for windows 10.
> 
> I have managed to install it on windows 10 after few modifications though, I'll run some testing and maybe push a patch later if everything is all right.

How did you do it?

**Comment by Jornker** [comment]
> OK, I think the simplest reason why this does not work is because the install script for tensorboardX is written in bash and not designed for windows 10.
> 
> I have managed to install it on windows 10 after few modifications though, I'll run some testing and maybe push a patch later if everything is all right.

will you be pushing a patch soon?

**Comment by Glamurio** [comment]
The issue is resolved for me by doing the following:
https://github.com/openai/jukebox/issues/53#issuecomment-655855448

**Comment by cicinwad** [comment]
> Any updates?
> I have the same issue, trying to install on Windows 10.

You need Install to windows 8.1, before using openai jukebox
