### ISSUE TITLE
NameError: name '_get_default_group' is not defined

### ISSUE THREAD

**Issue by HangAround47** [openai/jukebox#218]
Hi!
This happens when I want to try to train the model:

python jukebox/train.py --hps=small_vqvae --name=small_vqvae --sample_length=262144 --bs=4 --audio_files_dir=sanmp3 --labels=False --train --aug_shift --aug_blend
Using cuda True
Found 79 files. Getting durations
self.sr=22050, min: 12, max: inf
Keeping 77 of 79 files
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
Estimating duration from bitrate, this may be inaccurate
{'l2': 0.016028581976191468, 'l1': 0.09432193525560592, 'spec': 2703.2033268855166}
Creating Data Loader
Train 486 samples. Test 55 samples
Train sampler: <torch.utils.data.sampler.BatchSampler object at 0x000001C341B35FC8>
Train loader: 30
Loading vqvae in train mode
Parameters VQVAE:586050
Traceback (most recent call last):
  File "jukebox/train.py", line 345, in <module>
    fire.Fire(run)
  File "C:\Users\Creator\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\Creator\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\Creator\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/train.py", line 318, in run
    distributed_model = get_ddp(model, hps)
  File "jukebox/train.py", line 45, in get_ddp
    ddp = DistributedDataParallel(model, device_ids=[local_rank], output_device=local_rank, broadcast_buffers=False, bucket_cap_mb=hps.bucket)
  File "C:\Users\Creator\miniconda3\envs\jukebox\lib\site-packages\torch\nn\parallel\distributed.py", line 273, in __init__
    self.process_group = _get_default_group()
NameError: name '_get_default_group' is not defined

My operating system is win10, is it caused by the problem of dependency installation? Thank you!

**Comment by nuJack** [comment]
I'm also having this issue... Does anyone have an idea of what may be causing this issue?

**Comment by sunzeyucmu** [comment]
+1 here, on windows 10.

**Comment by cicinwad** [comment]
> Hi! This happens when I want to try to train the model:
> 
> python jukebox/train.py --hps=small_vqvae --name=small_vqvae --sample_length=262144 --bs=4 --audio_files_dir=sanmp3 --labels=False --train --aug_shift --aug_blend Using cuda True Found 79 files. Getting durations self.sr=22050, min: 12, max: inf Keeping 77 of 79 files Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate Estimating duration from bitrate, this may be inaccurate {'l2': 0.016028581976191468, 'l1': 0.09432193525560592, 'spec': 2703.2033268855166} Creating Data Loader Train 486 samples. Test 55 samples Train sampler: <torch.utils.data.sampler.BatchSampler object at 0x000001C341B35FC8> Train loader: 30 Loading vqvae in train mode Parameters VQVAE:586050 Traceback (most recent call last): File "jukebox/train.py", line 345, in fire.Fire(run) File "C:\Users\Creator\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 127, in Fire component_trace = _Fire(component, args, context, name) File "C:\Users\Creator\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 366, in _Fire component, remaining_args) File "C:\Users\Creator\miniconda3\envs\jukebox\lib\site-packages\fire\core.py", line 542, in _CallCallable result = fn(*varargs, **kwargs) File "jukebox/train.py", line 318, in run distributed_model = get_ddp(model, hps) File "jukebox/train.py", line 45, in get_ddp ddp = DistributedDataParallel(model, device_ids=[local_rank], output_device=local_rank, broadcast_buffers=False, bucket_cap_mb=hps.bucket) File "C:\Users\Creator\miniconda3\envs\jukebox\lib\site-packages\torch\nn\parallel\distributed.py", line 273, in **init** self.process_group = _get_default_group() NameError: name '_get_default_group' is not defined
> 
> My operating system is win10, is it caused by the problem of dependency installation? Thank you!

Your os needs to be win8 or win8.1: https://www.microsoft.com/en-us/software-download/windows8ISO
