### ISSUE TITLE
"Using cuda False" with RTX 3080

### ISSUE THREAD

**Issue by PladsElsker** [openai/jukebox#277]
I followed the instructions on the readme, I tried installing it 2 times, but I'm getting the same error (I'm running this command in the conda command line):
```
(jukebox) C:\Users\Plads\Documents\GitHub\openai_jukebox\jukebox>python jukebox/sample.py --model=1b_lyrics --name=sample_1b --levels=3 --sample_length_in_seconds=20 --total_sample_length_in_seconds=180 --sr=44100 --n_samples=16 --hop_fraction=0.5,0.5,0.125
Using cuda False
Traceback (most recent call last):
  File "jukebox/sample.py", line 279, in <module>
    fire.Fire(run)
  File "C:\Users\Plads\.conda\envs\jukebox\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\Plads\.conda\envs\jukebox\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\Plads\.conda\envs\jukebox\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/sample.py", line 271, in run
    rank, local_rank, device = setup_dist_from_mpi(port=port)
  File "c:\users\plads\documents\github\openai_jukebox\jukebox\jukebox\utils\dist_utils.py", line 55, in setup_dist_from_mpi
    torch.cuda.set_device(local_rank)
  File "C:\Users\Plads\.conda\envs\jukebox\lib\site-packages\torch\cuda\__init__.py", line 292, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```
I'm confused as to why this happens, as I have an RTX 3080, and if I believe what others have said, this should be enough to run the 1b_lyrics model. Am I missing a flag? Why does it not use my gpu? 

I looked in the issues of this repo, but I didn't really find anything helpful. 

Side-note: I also tried running 2 different google collabs, but I'm getting a bunch of errors there too... I think I'm getting very unlucky with this jukebox project xD
If anyone has good pointers as to why I'm getting this error, please let me know! I'd love to try this project.

**Comment by CCpt5** [comment]
There is a great discord server for Jukebox. You'll likely be able to find other discussions (From search) or help from someone in the chat: 

Here's an invite link: **https://discord.gg/wGvUbPnW**

**Comment by Ac31415** [comment]
> There is a great discord server for Jukebox. You'll likely be able to find other discussions (From search) or help from someone in the chat: 
> 
> 
> 
> Here's an invite link: **https://discord.gg/wGvUbPnW**

The link doesn't work....

**Comment by John-WL** [comment]
I think this reddot thread links the same server:
https://www.reddit.com/r/Openaijukebox/comments/mo2nzn/jukebox_discord/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by jaideep2** [comment]
@CCpt5 can i get an invite too? same problem & thanks

**Comment by CCpt5** [comment]
> @CCpt5 can i get an invite too? same problem & thanks

Sure: https://discord.gg/PxyeNuz8
