### ISSUE TITLE
RuntimeError during Sampling and thus error during training

### ISSUE THREAD

**Issue by Correlation4** [openai/jukebox#48]
I ran sample.py for 8h before CUDA ran out of memory. Here are the logs:
Input:
`~/jukebox$ python jukebox/sample.py --model=5b_lyrics --name=sample_5b --levels=3 --sample_length_in_seconds=20 --total_sample_length_in_seconds=180 --sr=44100 --n_samples=6 --hop_fraction=0.5,0.5,0.125`
Output:
```
Using cuda True
{'name': 'sample_5b', 'levels': 3, 'sample_length_in_seconds': 20, 'total_sample_length_in_seconds': 180, 'sr': 44100, 'n_samples': 6, 'hop_fraction': (0.5, 0.5, 0.125)}
Setting sample length to 881920 (i.e. 19.998185941043083 seconds) to be multiple of 128
Downloading from gce
Restored from /home/correlation4/.cache/jukebox-assets/models/5b/vqvae.pth.tar
0: Loading vqvae in eval mode
Conditioning on 1 above level(s)
Checkpointing convs
Checkpointing convs
Loading artist IDs from /home/correlation4/jukebox/jukebox/data/ids/v2_artist_ids.txt
Loading artist IDs from /home/correlation4/jukebox/jukebox/data/ids/v2_genre_ids.txt
Level:0, Cond downsample:4, Raw to tokens:8, Sample length:65536
Downloading from gce
Restored from /home/correlation4/.cache/jukebox-assets/models/5b/prior_level_0.pth.tar
0: Loading prior in eval mode
Conditioning on 1 above level(s)
Checkpointing convs
Checkpointing convs
Loading artist IDs from /home/correlation4/jukebox/jukebox/data/ids/v2_artist_ids.txt
Loading artist IDs from /home/correlation4/jukebox/jukebox/data/ids/v2_genre_ids.txt
Level:1, Cond downsample:4, Raw to tokens:32, Sample length:262144
Downloading from gce
Restored from /home/correlation4/.cache/jukebox-assets/models/5b/prior_level_1.pth.tar
0: Loading prior in eval mode
Loading artist IDs from /home/correlation4/jukebox/jukebox/data/ids/v2_artist_ids.txt
Loading artist IDs from /home/correlation4/jukebox/jukebox/data/ids/v2_genre_ids.txt
Level:2, Cond downsample:None, Raw to tokens:128, Sample length:1048576
0: Converting to fp16 params
Downloading from gce
Restored from /home/correlation4/.cache/jukebox-assets/models/5b_lyrics/prior_level_2.pth.tar
0: Loading prior in eval mode
Traceback (most recent call last):
  File "jukebox/sample.py", line 275, in <module>
    fire.Fire(run)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/sample.py", line 272, in run
    save_samples(model, device, hps, sample_hps)
  File "jukebox/sample.py", line 240, in save_samples
    ancestral_sample(labels, sampling_kwargs, priors, hps)
  File "jukebox/sample.py", line 123, in ancestral_sample
    zs = _sample(zs, labels, sampling_kwargs, priors, sample_levels, hps)
  File "jukebox/sample.py", line 94, in _sample
    prior.cuda()
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 1.96 GiB total capacity; 1.83 GiB already allocated; 2.75 MiB free; 1.87 GiB reserved in total by PyTorch)
```
I then decided to run a small vqvae in order to check if the sampling was effective (because i have no real idea of what this first part should output if it succeed).
Input:
`mpiexec -n 1 python jukebox/train.py --hps=small_vqvae --name=small_vqvae --sample_length=262144 --bs=4 --nworkers=4 --audio_files_dir=/home/correlation4/Downloads --labels=False --train --aug_shift --aug_blend`
Output:
```
Using cuda True
0: Found 15 files. Getting durations
0: self.sr=22050, min: 12, max: inf
0: Keeping 15 of 15 files
Traceback (most recent call last):
  File "jukebox/train.py", line 336, in <module>
    fire.Fire(run)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/correlation4/anaconda3/envs/jukebox2/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/train.py", line 294, in run
    data_processor = DataProcessor(hps)
  File "/home/correlation4/jukebox/jukebox/data/data_processor.py", line 28, in __init__
    hps.bandwidth = calculate_bandwidth(self.dataset, hps, duration=duration)
  File "/home/correlation4/jukebox/jukebox/utils/audio_utils.py", line 28, in calculate_bandwidth
    x = dataset[idx]
  File "/home/correlation4/jukebox/jukebox/data/files_dataset.py", line 96, in __getitem__
    return self.get_item(item)
  File "/home/correlation4/jukebox/jukebox/data/files_dataset.py", line 89, in get_item
    index, offset = self.get_index_offset(item)
  File "/home/correlation4/jukebox/jukebox/data/files_dataset.py", line 60, in get_index_offset
    assert 0 <= midpoint < self.cumsum[-1], f'Midpoint {midpoint} of item beyond total length {self.cumsum[-1]}'
AssertionError: Midpoint 12720168 of item beyond total length 11970543
```
Is there any link between the fact that CUDA ran out of memory and this error ? It seems like this error comes from somewhere else.

**Comment by prafullasd** [comment]
The second error comes from having too little data, you have 15 files and the function `calculate_bandwidth` by default iterates over about 600 sec of audio. Try passing a smaller duration to it.

**Comment by prafullasd** [comment]
How much CUDA memory do you have? The 5b_lyrics model needs 16GB for the default hps. Try lowering max_batch_size from 3 to say 1 in sample.py?

**Comment by Correlation4** [comment]
Thanks for the answers. I have a GeForce 740M, a low-end GPU, with only 2GB of memory, therefore I guess that's what CUDA has, which is far from ideal. 
That's also what the sampling command outputs when it fails to allocate more memory.
`RuntimeError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 1.96 GiB total capacity; 1.83 GiB already allocated; 2.75 MiB free; 1.87 GiB reserved in total by PyTorch)`

I'm not too sure what the sampling part is compared to the training part. I think i'll have to read the paper more in depth.
However, I have now more than 800s of audio to work with, but I still get a similar error (now with other values in the AssertionError message) :
`AssertionError: Midpoint 21112952 of item beyond total length 20853793`
Is there anything I did wrong, or is it just an hardware limitation due to my GPU?

**Comment by heewooj** [comment]
>  the function calculate_bandwidth by default iterates over about 600 sec of audio. Try passing a smaller duration to it.

The above error is not due to GPU. Could you try lowering 600 seconds to a smaller value?

> Training the small_prior with a batch size of 2, 4, and 8 requires 6.7 GB, 9.3 GB, and 15.8 GB of GPU memory

2GB is perhaps not enough. You may want to make `small_prior` smaller in width or depth. For VQ-VQAE training, you may want to decrease `--sample_length`
