### ISSUE TITLE
Training Issue - AssertionError: Midpoint 42164118 of item beyond total length 38873664

### ISSUE THREAD

**Issue by whatdamath** [openai/jukebox#59]
I'm trying to train a new model using the provided instructions but no matter how many wav files I put in or what length they are I always get the error below: 

> Traceback (most recent call last):
>   File "jukebox/train.py", line 336, in <module>
>     fire.Fire(run)
>   File "/home/anton/anaconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
>     component_trace = _Fire(component, args, context, name)
>   File "/home/anton/anaconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
>     component, remaining_args)
>   File "/home/anton/anaconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
>     result = fn(*varargs, **kwargs)
>   File "jukebox/train.py", line 294, in run
>     data_processor = DataProcessor(hps)
>   File "/home/anton/Documents/deep/jukebox/jukebox/data/data_processor.py", line 28, in __init__
>     hps.bandwidth = calculate_bandwidth(self.dataset, hps, duration=duration)
>   File "/home/anton/Documents/deep/jukebox/jukebox/utils/audio_utils.py", line 28, in calculate_bandwidth
>     x = dataset[idx]
>   File "/home/anton/Documents/deep/jukebox/jukebox/data/files_dataset.py", line 96, in __getitem__
>     return self.get_item(item)
>   File "/home/anton/Documents/deep/jukebox/jukebox/data/files_dataset.py", line 89, in get_item
>     index, offset = self.get_index_offset(item)
>   File "/home/anton/Documents/deep/jukebox/jukebox/data/files_dataset.py", line 60, in get_index_offset
>     assert 0 <= midpoint < self.cumsum[-1], f'Midpoint {midpoint} of item beyond total length {self.cumsum[-1]}'
> AssertionError: Midpoint 42164118 of item beyond total length 38873664
> 

Running this on a 11GB 1080Ti and had a few CUDA errors before, but with pretrained samples it eventually worked. Here though, it seems to be an error with midpoint being calculated wrong, but despite reading through the code, I can't figure out what's wrong

**Comment by apeguero1** [comment]
Hmm... seems like calculate_bandwidth is trying to access an item of music that's larger than the length of FilesAudioDataset. Maybe try adding a condition to the while loop to prevent that?
Something like `while n_seen < n_samples and idx < len(dataset):` right above line 28 in audio_utils.py

**Comment by whatdamath** [comment]
Ah perfect, this worked. Although I also had to lower the sample_length to
131072 - it looks like 11GB is not enough to run this
Thanks!

**Comment by apeguero1** [comment]
Nice! no problem.

**Comment by ObscuraDK** [comment]
I have just added the 'while loop' as described above, which let me go a little bit further, but now I am running into a new AssertionError.

0/96 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "jukebox/train.py", line 342, in <module>
    fire.Fire(run)
  File "/home/vertigo/miniconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/vertigo/miniconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/vertigo/miniconda3/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/train.py", line 325, in run
    train_metrics = train(distributed_model, model, opt, shd, scalar, ema, logger, metrics, data_processor, hps)
  File "jukebox/train.py", line 227, in train
    x_out, loss, _metrics = model(x, **forw_kwargs)
  File "/home/vertigo/miniconda3/envs/jukebox/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vertigo/miniconda3/envs/jukebox/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 376, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/vertigo/miniconda3/envs/jukebox/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vertigo/jukebox/jukebox/vqvae/vqvae.py", line 168, in forward
    assert_shape(x_out, x_in.shape)
  File "/home/vertigo/jukebox/jukebox/utils/torch_utils.py", line 25, in assert_shape
    assert x.shape == exp_shape, f"Expected {exp_shape} got {x.shape}"
AssertionError: Expected torch.Size([4, 1, 131000]) got torch.Size([4, 1, 130976])

**Comment by perlman-izzy** [comment]
Hi, pretty much a noob here: does anybody know how to fix:

 "file "jukebox/sample.py", line 279, in <module>
fire.Fire(run)
File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
component_trace = _Fire(component, args, context, name)
File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
component, remaining_args)
File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
result = fn(varargs, *kwargs)
File "jukebox/sample.py", line 276, in run
save_samples(model, device, hps, sample_hps)
File "jukebox/sample.py", line 258, in save_samples
assert sample_hps.audio_file is not None
AssertionError
"
