### ISSUE TITLE
Issues when trying to add new genre label when training with labels

### ISSUE THREAD

**Issue by btrude** [openai/jukebox#81]
Hi, I'm running into an issue trying to train a dataset from scratch with labels (but no lyrics). In the readme, there is an instruction like: `Update the v3_artist_ids and v3_genre_ids to use ids from your new dataset.` but that is slightly unclear. If you add a new genre;id or artist;id row and pass the new number(s) in y_bins you will later fail an assertion `(y < self.bins).all()` in `conditioner.py`. 

```
Traceback (most recent call last):
  File "jukebox/train.py", line 342, in <module>
    fire.Fire(run)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/train.py", line 325, in run
    train_metrics = train(distributed_model, model, opt, shd, scalar, ema, logger, metrics, data_processor, hps)
  File "jukebox/train.py", line 227, in train
    x_out, loss, _metrics = model(x, **forw_kwargs)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/btrude/Documents/workspace/jukebox/jukebox/prior/prior.py", line 345, in forward
    loss, metrics = self.z_forward(z=z, z_conds=z_conds, y=y, fp16=fp16, get_preds=get_preds)
  File "/home/btrude/Documents/workspace/jukebox/jukebox/prior/prior.py", line 319, in z_forward
    x_cond, y_cond, prime = self.get_cond(z_conds, y)
  File "/home/btrude/Documents/workspace/jukebox/jukebox/prior/prior.py", line 237, in get_cond
    y_cond, y_pos = self.y_emb(y) if self.y_cond else (None, None)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/btrude/Documents/workspace/jukebox/jukebox/prior/conditioners.py", line 145, in forward
    genre_emb = (self.bow_genre_emb(genre.clamp(0)) * mask).sum(dim=1, keepdim=True)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/btrude/Documents/workspace/jukebox/jukebox/prior/conditioners.py", line 67, in forward
    assert (0 <= y).all() and (y < self.bins).all(), f"Bins {self.bins}, got label {y}"
AssertionError: Bins 604, got label tensor([[604],
        [604],
        [604],
        [604],
        [604],
        [604],
        [604],
        [604],
        [604],
        [604]], device='cuda:0')
```

Replacing an existing genre with the new genre sidesteps this issue for the first round of sampling, but then fails with the below stack trace.
```
Traceback (most recent call last):
  File "jukebox/train.py", line 342, in <module>
    fire.Fire(run)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/train.py", line 325, in run
    train_metrics = train(distributed_model, model, opt, shd, scalar, ema, logger, metrics, data_processor, hps)
  File "jukebox/train.py", line 277, in train
    sample_prior(orig_model, ema, logger, x_in, y, hps)
  File "jukebox/train.py", line 141, in sample_prior
    log_labels(logger, orig_model.labeller, f'sample_x_T1', allgather(y.cuda()), hps)
  File "jukebox/train.py", line 36, in log_labels
    description = labeller.describe_label(y[item])
  File "/home/btrude/Documents/workspace/jukebox/jukebox/data/labels.py", line 92, in describe_label
    tokens = y[-self.n_tokens:]
ValueError: not enough values to unpack (expected at least 4, got 0)
```

The above problem is caused by a n_tokens value of 0 causing the slice to return an empty list (but only after the first round of sampling??). Setting n_tokens=0 as an hparam resolves the above issue, but then results in the following stack trace shortly thereafter:

```
Traceback (most recent call last):
  File "jukebox/train.py", line 342, in <module>
    fire.Fire(run)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/btrude/Documents/workspace/jukebox/.venv/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/train.py", line 325, in run
    train_metrics = train(distributed_model, model, opt, shd, scalar, ema, logger, metrics, data_processor, hps)
  File "jukebox/train.py", line 277, in train
    sample_prior(orig_model, ema, logger, x_in, y, hps)
  File "jukebox/train.py", line 141, in sample_prior
    log_labels(logger, orig_model.labeller, f'sample_x_T1', allgather(y.cuda()), hps)
  File "jukebox/train.py", line 36, in log_labels
    description = labeller.describe_label(y[item])
  File "/home/btrude/Documents/workspace/jukebox/jukebox/data/labels.py", line 98, in describe_label
    
  File "/home/btrude/Documents/workspace/jukebox/jukebox/data/text_processor.py", line 29, in textise
    return ''.join([self.tokens[token] for token in tokens])
  File "/home/btrude/Documents/workspace/jukebox/jukebox/data/text_processor.py", line 29, in <listcomp>
    return ''.join([self.tokens[token] for token in tokens])
KeyError: 15358358
```

Obviously feeling a bit lost here and would appreciate any help to get this going. Training works as expected without labels so I suspect that the instructions are incomplete or I am just doing something wrong in this case. Thanks!

**Comment by TomReid013** [comment]
did this ever get solved im getting a similar error when trying to train with labels after adding one new artist and 1 new genre
```
Traceback (most recent call last):
  File "jukebox/train.py", line 345, in <module>
    fire.Fire(run)
  File "/home/tom/anaconda3/envs/juke/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/tom/anaconda3/envs/juke/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/tom/anaconda3/envs/juke/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/train.py", line 328, in run
    train_metrics = train(distributed_model, model, opt, shd, scalar, ema, logger, metrics, data_processor, hps)
  File "jukebox/train.py", line 230, in train
    x_out, loss, _metrics = model(x, **forw_kwargs)
  File "/home/tom/anaconda3/envs/juke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tom/anaconda3/envs/juke/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 904, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/tom/anaconda3/envs/juke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tom/Downloads/jukebox/jukebox/prior/prior.py", line 349, in forward
    loss, metrics = self.z_forward(z=z, z_conds=z_conds, y=y, fp16=fp16, get_preds=get_preds)
  File "/home/tom/Downloads/jukebox/jukebox/prior/prior.py", line 323, in z_forward
    x_cond, y_cond, prime = self.get_cond(z_conds, y)
  File "/home/tom/Downloads/jukebox/jukebox/prior/prior.py", line 241, in get_cond
    y_cond, y_pos = self.y_emb(y) if self.y_cond else (None, None)
  File "/home/tom/anaconda3/envs/juke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tom/Downloads/jukebox/jukebox/prior/conditioners.py", line 142, in forward
    artist_emb = self.artist_emb(artist)
  File "/home/tom/anaconda3/envs/juke/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1106, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tom/Downloads/jukebox/jukebox/prior/conditioners.py", line 67, in forward
    assert (0 <= y).all() and (y < self.bins).all(), f"Bins {self.bins}, got label {y}"
AssertionError: Bins 7898, got label tensor([[7898],
        [7898],
        [7898],
        [7898]], device='cuda:0')


```
